#!/usr/bin/env python3
"""
TOP 100 NEWS SOURCES - RSS Feeds for Radio Pipeline
Curated list of working RSS feeds across all categories.
Includes tech (ixbt, habr), AI, space, politics, war, finance, crypto, culture, science, etc.
"""

TOP_100_RSS_FEEDS = {
    # === TECH / IT / PROGRAMMING ===
    "tech": {
        "ixbt": "https://www.ixbt.com/export/news.rss",
        "habr": "https://habr.com/ru/rss/all/all/",
        "habr_en": "https://habr.com/en/rss/all/all/",
        "vc_ru": "https://vc.ru/rss",
        "tproger": "https://tproger.ru/feed/",
        "hitech": "https://hi-news.ru/feed/",
        "3dnews": "https://3dnews.ru/feed/",
        "cnews": "https://www.cnews.ru/inc/rss/news_top.rss",
        "securitylab": "https://www.securitylab.ru/_services/export/rss/",
        "opennet": "https://www.opennet.ru/opennews/opennews_all.rss",
        "linux_org_ru": "https://www.linux.org.ru/rss/news.xml",
        "proglib": "https://proglib.io/rss",
        "skillbox": "https://skillbox.ru/media/feed/",
        "yandex_tech": "https://yandex.ru/blog/company/rss",
    },

    # === AI / ML / DATA SCIENCE ===
    "ai_ml": {
        "huggingface": "https://huggingface.co/blog/feed.xml",
        "openai": "https://openai.com/blog/rss.xml",
        "deepmind": "https://deepmind.com/blog/feed.xml",
        "anthropic": "https://www.anthropic.com/feed.xml",
        "karpathy": "https://karpathy.github.io/feed.xml",
        "google_ai": "https://ai.googleblog.com/feeds/posts/default",
        "meta_ai": "https://ai.facebook.com/blog/rss/",
        "nvidia_ai": "https://blogs.nvidia.com/category/ai/feed/",
        "ml_blog": "https://blog.ml.cmu.edu/feed/",
        "distill": "https://distill.pub/rss.xml",
        "papers_with_code": "https://paperswithcode.com/rss",
        "arxiv_ai": "https://arxiv.org/rss/cs.AI",
        "arxiv_ml": "https://arxiv.org/rss/cs.LG",
        "arxiv_cl": "https://arxiv.org/rss/cs.CL",
        "arxiv_cv": "https://arxiv.org/rss/cs.CV",
        "openreview": "https://openreview.net/rss",
        "ai_weekly": "https://aiweekly.co/issues.rss",
        "the_gradient": "https://thegradient.pub/feed/",
        "synced": "https://syncedreview.com/feed/",
    },

    # === SPACE / ASTRONOMY ===
    "space": {
        "nasa": "https://www.nasa.gov/rss/dyn/breaking_news.rss",
        "nasa_science": "https://science.nasa.gov/rss.xml",
        "spacex": "https://www.spacex.com/news/rss/",
        "space_com": "https://www.space.com/feeds/all",
        "nasaspaceflight": "https://www.nasaspaceflight.com/feed/",
        "esa": "https://www.esa.int/rss/esa_news.xml",
        "esa_science": "https://www.esa.int/rss/esa_science.xml",
        "spacepolicy": "https://www.spacepolicyonline.com/feed/",
        "planetary": "https://www.planetary.org/rss.xml",
        "skyandtelescope": "https://skyandtelescope.org/feed/",
        "astronomy_com": "https://www.astronomy.com/feed/",
        "space_ref": "https://spaceref.com/feed/",
        "parabolic_arc": "https://www.parabolicarc.com/feed/",
        "nextbigfuture": "https://www.nextbigfuture.com/feed/",
        "universe_today": "https://www.universetoday.com/feed/",
    },

    # === SCIENCE / RESEARCH ===
    "science": {
        "nature": "https://www.nature.com/nature.rss",
        "science_mag": "https://www.science.org/rss/news_current.xml",
        "scientific_american": "https://www.scientificamerican.com/feed/",
        "new_scientist": "https://www.newscientist.com/feed/home/",
        "phys_org": "https://phys.org/rss-feed/",
        "eurekalert": "https://www.eurekalert.org/rss.xml",
        "sciencedaily": "https://www.sciencedaily.com/rss/all.xml",
        "quantamagazine": "https://www.quantamagazine.org/feed/",
        "plos": "https://journals.plos.org/plosone/feed/atom",
        "cell": "https://www.cell.com/rss",
        "mit_news": "https://news.mit.edu/rss",
        "caltech": "https://www.caltech.edu/about/news/rss",
        "stanford": "https://news.stanford.edu/feed/",
        "harvard": "https://news.harvard.edu/gazette/feed/",
    },

    # === POLITICS / WORLD NEWS ===
    "politics": {
        "reuters_world": "https://feeds.reuters.com/reuters/worldNews",
        "reuters_politics": "https://feeds.reuters.com/reuters/politicsNews",
        "bbc_world": "https://feeds.bbci.co.uk/news/world/rss.xml",
        "bbc_politics": "https://feeds.bbci.co.uk/news/politics/rss.xml",
        "ap_news": "https://apnews.com/rss",
        "nytimes_world": "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
        "nytimes_politics": "https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml",
        "wapo_world": "https://www.washingtonpost.com/world/rss.xml",
        "wapo_politics": "https://www.washingtonpost.com/politics/rss.xml",
        "guardian_world": "https://www.theguardian.com/world/rss",
        "guardian_politics": "https://www.theguardian.com/politics/rss",
        "economist": "https://www.economist.com/feed.xml",
        "foreign_policy": "https://foreignpolicy.com/rss.xml",
        "politico": "https://www.politico.com/rss/politics08.xml",
        "axios": "https://www.axios.com/feed.xml",
        "bloomberg_politics": "https://www.bloomberg.com/politics/feed.xml",
    },

    # === WAR / CONFLICT / DEFENSE ===
    "war": {
        "reuters_ukraine": "https://www.reuters.com/world/ukraine/feed/",
        "bbc_ukraine": "https://feeds.bbci.co.uk/news/world/europe/rss.xml",
        "isw": "https://www.understandingwar.org/feed",
        "isw_russia": "https://www.understandingwar.org/taxonomy/term/522/feed",
        "kyiv_independent": "https://kyivindependent.com/feed/",
        "euromaidan": "https://euromaidanpress.com/feed/",
        "military_com": "https://www.military.com/rss",
        "defense_news": "https://www.defensenews.com/arc/outboundfeeds/rss/?outputType=xml",
        "breaking_defense": "https://breakingdefense.com/feed/",
        "war_on_rocks": "https://warontherocks.com/feed/",
        "rusi": "https://rusi.org/rss.xml",
        "c4isrnet": "https://www.c4isrnet.com/arc/outboundfeeds/rss/?outputType=xml",
        "naval_news": "https://www.navalnews.com/feed/",
        "airforce_mag": "https://www.airforcemag.com/feed/",
        "army_times": "https://www.armytimes.com/arc/outboundfeeds/rss/?outputType=xml",
    },

    # === FINANCE / ECONOMICS / MARKETS ===
    "finance": {
        "bloomberg": "https://www.bloomberg.com/feed.xml",
        "bloomberg_markets": "https://www.bloomberg.com/markets/feed.xml",
        "reuters_business": "https://feeds.reuters.com/reuters/businessNews",
        "ft": "https://www.ft.com/rss/home/world",
        "ft_markets": "https://www.ft.com/rss/home/markets",
        "wsj": "https://www.wsj.com/xml/rss/3_7014.xml",
        "wsj_markets": "https://www.wsj.com/xml/rss/3_7031.xml",
        "economist_finance": "https://www.economist.com/finance-and-economics/rss.xml",
        "cnbc": "https://www.cnbc.com/id/100003114/device/rss/rss.html",
        "marketwatch": "https://feeds.marketwatch.com/marketwatch/topstories/",
        "yahoo_finance": "https://finance.yahoo.com/rss/",
        "investing": "https://www.investing.com/rss/news_25.rss",
        "zerohedge": "https://www.zerohedge.com/feed",
        "seeking_alpha": "https://seekingalpha.com/market_currents.xml",
        "morningstar": "https://news.morningstar.com/rss",
        "federal_reserve": "https://www.federalreserve.gov/feeds/press_all.xml",
        "ecb": "https://www.ecb.europa.eu/rss/html/index.en.html",
        "imf": "https://www.imf.org/en/News/RSS",
        "world_bank": "https://www.worldbank.org/en/news/rss",
    },

    # === CRYPTO / BLOCKCHAIN / WEB3 ===
    "crypto": {
        "coindesk": "https://www.coindesk.com/arc/outboundfeeds/rss/",
        "theblock": "https://www.theblock.co/rss.xml",
        "cointelegraph": "https://cointelegraph.com/rss",
        "decrypt": "https://decrypt.co/feed",
        "bitcoin_magazine": "https://bitcoinmagazine.com/feed",
        "coindesk_policy": "https://www.coindesk.com/policy/feed/",
        "defillama": "https://defillama.com/rss.xml",
        "messari": "https://messari.io/feed",
        "bankless": "https://www.banklesshq.com/feed",
        "a16z_crypto": "https://a16zcrypto.com/feed/",
        "paradigm": "https://www.paradigm.xyz/feed",
        "electric_capital": "https://electriccapital.com/feed/",
        "variant_fund": "https://www.variant.fund/feed",
        "crypto_briefing": "https://cryptobriefing.com/feed/",
        "u_today": "https://u.today/rss",
        "beincrypto": "https://beincrypto.com/feed/",
        "crypto_potato": "https://cryptopotato.com/feed/",
        "daily_hodl": "https://dailyhodl.com/feed/",
        "newsbtc": "https://www.newsbtc.com/feed/",
        "coindesk_jp": "https://www.coindeskjapan.com/feed/",
        "coinpost": "https://coinpost.jp/feed/",
    },

    # === CULTURE / ENTERTAINMENT ===
    "culture": {
        "variety": "https://variety.com/feed/",
        "hollywood_reporter": "https://www.hollywoodreporter.com/feed/",
        "deadline": "https://deadline.com/feed/",
        "indiewire": "https://www.indiewire.com/feed/",
        "screen_rant": "https://screenrant.com/feed/",
        "collider": "https://collider.com/feed/",
        "the_verge_film": "https://www.theverge.com/film/rss/index.xml",
        "rolling_stone": "https://www.rollingstone.com/feed/",
        "pitchfork": "https://pitchfork.com/rss/news/",
        "stereogum": "https://www.stereogum.com/feed/",
        "consequence": "https://consequence.net/feed/",
        "nme": "https://www.nme.com/feed/",
        "billboard": "https://www.billboard.com/feed/",
        "grammy": "https://www.grammy.com/feed",
        "ted": "https://www.ted.com/feed",
        "new_yorker": "https://www.newyorker.com/feed/culture",
        "atlantic_culture": "https://www.theatlantic.com/feed/channel/culture/",
        "smithsonian": "https://www.smithsonianmag.com/rss/",
        "national_geographic": "https://www.nationalgeographic.com/rss.xml",
    },

    # === GAMING / ESPORTS ===
    "gaming": {
        "ign": "https://feeds.ign.com/ign/all",
        "gamespot": "https://www.gamespot.com/feeds/mashup/",
        "polygon": "https://www.polygon.com/rss/index.xml",
        "kotaku": "https://kotaku.com/rss",
        "eurogamer": "https://www.eurogamer.net/rss.xml",
        "pc_gamer": "https://www.pcgamer.com/rss/",
        "game_informer": "https://www.gameinformer.com/rss",
        "dexerto": "https://www.dexerto.com/feed",
        "esports_insider": "https://esportsinsider.com/feed/",
        "the_loadout": "https://theloadout.com/feed/",
        "rock_paper_shotgun": "https://www.rockpapershotgun.com/feed/",
        "vg247": "https://www.vg247.com/feed/",
        "gamesradar": "https://www.gamesradar.com/rss/",
        "steam_news": "https://store.steampowered.com/feeds/news.xml",
    },

    # === HARDWARE / GADGETS / CONSUMER TECH ===
    "hardware": {
        "anandtech": "https://www.anandtech.com/rss",
        "tomshardware": "https://www.tomshardware.com/feeds/all",
        "techpowerup": "https://www.techpowerup.com/rss.xml",
        "guru3d": "https://www.guru3d.com/rss-feeds/latest-news.rss",
        "videocardz": "https://videocardz.com/feed/",
        "wccftech": "https://wccftech.com/feed/",
        "hardware_times": "https://hardwaretimes.com/feed/",
        "kitguru": "https://www.kitguru.net/feed/",
        "overclock3d": "https://www.overclock3d.net/feed/",
        "tweaktown": "https://www.tweaktown.com/rss.xml",
        "notebookcheck": "https://www.notebookcheck.net/rss.xml",
        "laptopmag": "https://www.laptopmag.com/rss.xml",
        "android_authority": "https://www.androidauthority.com/feed/",
        "android_central": "https://www.androidcentral.com/rss.xml",
        "9to5google": "https://9to5google.com/feed/",
        "9to5mac": "https://9to5mac.com/feed/",
        "macrumors": "https://www.macrumors.com/feed/",
        "arstechnica_hardware": "https://arstechnica.com/gadgets/feed/",
        "engadget": "https://www.engadget.com/rss.xml",
        "the_verge_tech": "https://www.theverge.com/rss/index.xml",
        "gizmodo": "https://gizmodo.com/rss",
        "techradar": "https://www.techradar.com/rss",
        "t3": "https://www.t3.com/rss.xml",
        "stuff": "https://www.stuff.tv/rss.xml",
        "cnet": "https://www.cnet.com/rss/news/",
        "zdnet": "https://www.zdnet.com/news/rss.xml",
        "techcrunch_hardware": "https://techcrunch.com/tag/hardware/feed/",
    },

    # === AUTOMOTIVE / EV / MOBILITY ===
    "auto": {
        "electrek": "https://electrek.co/feed/",
        "insideevs": "https://insideevs.com/rss.xml",
        "teslarati": "https://www.teslarati.com/feed/",
        "car_and_driver": "https://www.caranddriver.com/rss.xml",
        "motor_trend": "https://www.motortrend.com/feed/",
        "road_and_track": "https://www.roadandtrack.com/rss.xml",
        "jalopnik": "https://jalopnik.com/rss",
        "the_drive": "https://www.thedrive.com/feed/",
        "autoblog": "https://www.autoblog.com/rss.xml",
        "motor1": "https://www.motor1.com/rss.xml",
        "cleantechnica": "https://cleantechnica.com/feed/",
        "green_car_reports": "https://www.greencarreports.com/rss.xml",
        "charged": "https://chargedevs.com/feed/",
        "ev_adoption": "https://evadoption.com/feed/",
    },

    # === HEALTH / MEDICINE / BIOTECH ===
    "health": {
        "nih": "https://www.nih.gov/news-events/news-releases/rss.xml",
        "who": "https://www.who.int/rss-feeds/news-english.xml",
        "cdc": "https://tools.cdc.gov/api/v2/resources/media/404832.rss",
        "nejm": "https://www.nejm.org/rss",
        "lancet": "https://www.thelancet.com/rssfeed.xml",
        "bmj": "https://www.bmj.com/rss",
        "jama": "https://jamanetwork.com/rss/site_news.xml",
        "nature_medicine": "https://www.nature.com/nmed.rss",
        "science_translational": "https://www.science.org/rss/translational.xml",
        "stat_news": "https://www.statnews.com/feed/",
        "fierce_biotech": "https://www.fiercebiotech.com/rss.xml",
        "fierce_pharma": "https://www.fiercepharma.com/rss.xml",
        "genome_web": "https://www.genomeweb.com/rss.xml",
        "bio_century": "https://www.biocentury.com/rss",
        "endpoints": "https://endpointsnews.com/feed/",
    },

    # === ENERGY / CLIMATE / ENVIRONMENT ===
    "energy": {
        "greentech_media": "https://www.greentechmedia.com/rss.xml",
        "pv_magazine": "https://www.pv-magazine.com/rss.xml",
        "windpower": "https://www.windpowermonthly.com/rss",
        "recharge": "https://www.rechargenews.com/rss",
        "energy_monitor": "https://theenergymonitor.ai/feed/",
        "carbon_brief": "https://www.carbonbrief.org/feed/",
        "climate_home": "https://www.climatechangenews.com/feed/",
        "iea": "https://www.iea.org/rss.xml",
        "eia": "https://www.eia.gov/rss/eia_news.xml",
        "bnef": "https://about.bnef.com/blog/feed/",
        "rmi": "https://rmi.org/feed/",
        "sierra_club": "https://www.sierraclub.org/rss.xml",
        "350_org": "https://350.org/feed/",
        "greenpeace": "https://www.greenpeace.org/international/rss/",
    },

    # === RUSSIAN LANGUAGE SOURCES ===
    "ru_tech": {
        "ixbt": "https://www.ixbt.com/export/news.rss",
        "habr": "https://habr.com/ru/rss/all/all/",
        "vc_ru": "https://vc.ru/rss",
        "tproger": "https://tproger.ru/feed/",
        "3dnews": "https://3dnews.ru/feed/",
        "cnews": "https://www.cnews.ru/inc/rss/news_top.rss",
        "securitylab": "https://www.securitylab.ru/_services/export/rss/",
        "opennet": "https://www.opennet.ru/opennews/opennews_all.rss",
        "linux_org_ru": "https://www.linux.org.ru/rss/news.xml",
        "ferra": "https://ferra.ru/rss",
        "droid": "https://droid.ru/rss.xml",
        "mobile_review": "https://mobile-review.com/rss.xml",
        "pcweek": "https://pcweek.ru/rss.xml",
        "computerworld_ru": "https://www.computerworld.ru/rss/",
        "itweek": "https://itweek.ru/rss.xml",
        "comnews": "https://comnews.ru/rss.xml",
        "rosbalt": "https://rosbalt.ru/rss.xml",
        "rbc_tech": "https://www.rbc.ru/technology_and_media/rss/",
        "vedomosti_tech": "https://www.vedomosti.ru/rss/rubric/technology.xml",
        "kommersant_tech": "https://www.kommersant.ru/rss/technology.xml",
    },

    "ru_politics": {
        "rbc": "https://www.rbc.ru/rss/",
        "vedomosti": "https://www.vedomosti.ru/rss/rubric/politics.xml",
        "kommersant": "https://www.kommersant.ru/rss/politics.xml",
        "rbc_politics": "https://www.rbc.ru/politics/rss/",
        "tass": "https://tass.ru/rss/v2.xml",
        "ria": "https://ria.ru/export/rss2/archive/index.xml",
        "rt_russian": "https://russian.rt.com/rss/",
        "gazeta": "https://www.gazeta.ru/export/rss/lenta.xml",
        "lenta": "https://lenta.ru/rss",
        "rbc_main": "https://www.rbc.ru/rss/main.rss",
        "vedomosti_main": "https://www.vedomosti.ru/rss/main.xml",
        "kommersant_main": "https://www.kommersant.ru/rss/main.xml",
        "rbc_economics": "https://www.rbc.ru/economics/rss/",
        "vedomosti_economics": "https://www.vedomosti.ru/rss/rubric/business.xml",
        "kommersant_business": "https://www.kommersant.ru/rss/business.xml",
    },

    "ru_war": {
        "ria_war": "https://ria.ru/export/rss2/archive/section_6.xml",
        "tass_war": "https://tass.ru/rss/v2.xml",
        "rbc_war": "https://www.rbc.ru/rss/section_6.rss",
        "lenta_war": "https://lenta.ru/rss/top7",
        "gazeta_war": "https://www.gazeta.ru/export/rss/war.xml",
        "rt_war": "https://russian.rt.com/rss/tag/war/",
        "meduza": "https://meduza.io/rss/all",
        "zona": "https://zona.media/rss",
        "bbc_russian": "https://feeds.bbci.co.uk/russian/rss.xml",
        "dw_russian": "https://rss.dw.com/rdf/rus-all_rss.xml",
        "svoboda": "https://www.svoboda.org/api/zprqevqprq",
        "current_time": "https://www.currenttime.tv/api/zprqevqprq",
        "agentstvo": "https://agentstvo.news/rss",
        "important_stories": "https://istories.media/rss",
        "proekt": "https://proekt.media/rss",
        "vert": "https://vert.media/rss",
    },
}

# Flatten for easy access
def get_all_feeds():
    """Return flat dict of category -> {source: url}"""
    return TOP_100_RSS_FEEDS

def get_feed_count():
    total = 0
    for cat, sources in TOP_100_RSS_FEEDS.items():
        total += len(sources)
    return total

if __name__ == "__main__":
    print(f"Total sources: {get_feed_count()}")
    for cat, sources in TOP_100_RSS_FEEDS.items():
        print(f"{cat}: {len(sources)} feeds")